# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java#apache-maven-with-a-settings-path

name: Java deployment with Maven [master]

on:
  workflow_dispatch:
  release:
    types: [created]

env:
  MAVEN_FLAGS: -B -s settings.xml -f pom.xml -DskipTests

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.11
        uses: actions/setup-java@v1
        with:
          java-version: 1.11
          server-id: github
      - name: Build with Maven
        env:
          GITHUB_ACCOUNT: ${{ github.actor }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_T
        run: mvn clean deploy ${{ env.MAVEN_FLAGS }}